name: Hospital App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # Используем одну из меток раннера
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: 192.168.1.14:3000
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEATOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: 192.168.1.14:3000/${{ gitea.repository_owner }}/hospital-app:latest
