[all:vars]
ansible_user=root
ansible_ssh_pass=temp123
ansible_python_interpreter=/usr/bin/python3
# В будущем, когда настроим ключи окончательно, пароль уберем

[nodes]
hospital-prod  ansible_host=10.6.1.17
hospital-dev   ansible_host=10.6.1.19
hospital-cicd  ansible_host=10.6.1.14

[app_nodes]
hospital-prod
hospital-dev

[cicd_nodes]
hospital-cicd
